### ISSUE TITLE
Saving Files From Chat Yields JS Error

### ISSUE THREAD

**Issue by daveman1010221** [snapcrafters/mattermost-desktop#34] opened 2020-11-16 22:02 UTC
I've been seeing this for a while, my normal work-around is to open the browser client and save file from chat.

Clicking on the file to save yields the following in syslog, which seems to be ok:

```
Nov 16 16:54:15 audit[28864]: AVC apparmor="ALLOWED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/etc/fstab" pid=28864 comm="mattermost-desk" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 16 16:54:15 kernel: audit: type=1400 audit(1605563655.678:271): apparmor="ALLOWED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/etc/fstab" pid=28864 comm="mattermost-desk" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 16 16:54:15 audit[28864]: AVC apparmor="ALLOWED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/run/mount/utab" pid=28864 comm="mattermost-desk" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 16 16:54:15 kernel: audit: type=1400 audit(1605563655.686:272): apparmor="ALLOWED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/run/mount/utab" pid=28864 comm="mattermost-desk" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 16 16:54:15 mattermost-desk[28864]: GtkDialog mapped without a transient parent. This is discouraged.
Nov 16 16:54:15 dbus-daemon[2014]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service' requested by ':1.173' (uid=1000 pid=28864 comm="/snap/mattermost-desktop/271/opt/Mattermost/matter" label="snap.mattermost-desktop.mattermost-desktop (complain)")
Nov 16 16:54:15 audit[28864]: AVC apparmor="ALLOWED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/run/mount/utab" pid=28864 comm="mattermost-desk" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 16 16:54:15 kernel: audit: type=1400 audit(1605563655.787:273): apparmor="ALLOWED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/run/mount/utab" pid=28864 comm="mattermost-desk" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 16 16:54:15 systemd[1]: Starting Hostname Service...
-- Subject: A start job for unit systemd-hostnamed.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit systemd-hostnamed.service has begun execution.
-- 
-- The job identifier is 8939.
Nov 16 16:54:15 dbus-daemon[2014]: [system] Successfully activated service 'org.freedesktop.hostname1'
Nov 16 16:54:15 systemd[1]: Started Hostname Service.
-- Subject: A start job for unit systemd-hostnamed.service has finished successfully
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
-- 
-- A start job for unit systemd-hostnamed.service has finished successfully.
-- 
-- The job identifier is 8939.
Nov 16 16:54:15 audit[2014]: USER_AVC pid=2014 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="ALLOWED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/hostname1" interface="org.freedesktop.DBus.Properties" member="GetAll" mask="send" name=":1.174" pid=28864 label="snap.mattermost-desktop.mattermost-desktop" peer_pid=31036 peer_label="unconfined"
                              exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
Nov 16 16:54:15 kernel: audit: type=1107 audit(1605563655.862:274): pid=2014 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="ALLOWED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/hostname1" interface="org.freedesktop.DBus.Properties" member="GetAll" mask="send" name=":1.174" pid=28864 label="snap.mattermost-desktop.mattermost-desktop" peer_pid=31036 peer_label="unconfined"
                         exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
Nov 16 16:54:15 audit[2014]: USER_AVC pid=2014 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="ALLOWED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/hostname1" interface="org.freedesktop.DBus.Properties" member="GetAll" mask="send" name=":1.174" pid=28864 label="snap.mattermost-desktop.mattermost-desktop" peer_pid=31036 peer_label="unconfined"
                              exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
Nov 16 16:54:15 kernel: audit: type=1107 audit(1605563655.863:275): pid=2014 uid=103 auid=4294967295 ses=4294967295 msg='apparmor="ALLOWED" operation="dbus_method_call"  bus="system" path="/org/freedesktop/hostname1" interface="org.freedesktop.DBus.Properties" member="GetAll" mask="send" name=":1.174" pid=28864 label="snap.mattermost-desktop.mattermost-desktop" peer_pid=31036 peer_label="unconfined"
                         exe="/usr/bin/dbus-daemon" sauid=103 hostname=? addr=? terminal=?'
```
I had to install the snap in devmode to prevent the above from being AppArmor errors.

Giving the file to save a name in gnome and clicking 'save' yields:

```
Nov 16 16:54:51 audit[28864]: AVC apparmor="ALLOWED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/run/mount/utab" pid=28864 comm="mattermost-desk" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 16 16:54:51 kernel: audit: type=1400 audit(1605563691.954:277): apparmor="ALLOWED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/run/mount/utab" pid=28864 comm="mattermost-desk" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 16 16:55:06 audit[28864]: AVC apparmor="ALLOWED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/run/mount/utab" pid=28864 comm="mattermost-desk" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 16 16:55:06 kernel: audit: type=1400 audit(1605563706.172:278): apparmor="ALLOWED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/run/mount/utab" pid=28864 comm="mattermost-desk" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
Nov 16 16:55:06 ubuntu-appindicators@ubuntu.com[4817]: Mattermost1, Impossible to lookup icon for 'Mattermost1_26-panel'
Nov 16 16:55:06 gnome-shell[4817]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                   _createIconByName@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:406:26
                                   _cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:368:14
                                   _updateIconByType@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:574:18
                                   _updateIcon@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:601:14
                                   _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                   _onPropertiesChanged/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:220:22
                                   _onPropertiesChanged@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/appIndicator.js:214:15
                                   refreshPropertyOnProxy/<@/usr/share/gnome-shell/extensions/ubuntu-appindicators@ubuntu.com/util.js:51:19
```

System is Ubuntu 20.04.
Mattermost version reports 4.6.1

I've hunted this until I've ran out of ideas. Maybe the snap is incompatible with Ubuntu 20.04 for the file save API?

**Comment by galgalesh** [comment] 2020-11-16 22:13
I cannot reproduce this error on default Ubuntu 20.04.

* Do you have any modifications that might cause this?
* What kind of files are you saving and does it happen with every file?
* In which locations are you saving these files?
* What is the Mattermost _server_ version?

**Comment by galgalesh** [comment] 2020-11-16 22:13
I cannot reproduce this error on default Ubuntu 20.04.

* Do you have any modifications that might cause this?
* What kind of files are you saving and does it happen with every file?
* In which locations are you saving these files?
* What is the Mattermost _server_ version?

**Comment by galgalesh** [comment] 2020-11-18 21:17
Note that depending on the location where you want to save a file, you need to give mattermost additional permissions; specifically the `removable-media` permission. You can do this via the permissions gui or by running 

```
snap connect mattermost-desktop:removable-media
```

**Comment by galgalesh** [comment] 2021-06-23 15:53
Closing issue due to lack of reproducability and response. Please reopen if you can provide the requested information.

**Closed by galgalesh** 2021-06-23 15:53 UTC
