### ISSUE TITLE
[Bug]: Downloads fail with 'Cancelled' for 5.2.1

### ISSUE THREAD

**Issue by mm-may** [snapcrafters/mattermost-desktop#65] opened 2022-11-23 16:36 UTC
### What happened?

On Ubuntu and Kubuntu 22.04, Downloading files from a conversion fail, irrespective of the file type. The preview works, but if one clicks on "Download" if fails and the little pop-up window 'Downloads' says the file download has been "Cancelled". This happens since version 5.2.0, but still there in 5.2.1. Downloading from Mattermost in the browser still works.

It looks like something is wrong with the apparmor profile, preventing the app to perform file operations.

### What should have happened?

When I click on download for a file, either directly on the 'download' button on the thumbnail or the download button on the full-screen preview, the download of the file fails.

### Output of `snap info $snap_name`

```shell
snap-id:      ed0pxJoDHrgmAWHH7baX5nryAHy1UNj0
tracking:     latest/candidate
refresh-date: 6 days ago, at 20:13 CET
channels:
  latest/stable:    5.2.1 2022-11-21 (567) 135MB -
  latest/candidate: 5.2.1 2022-11-17 (567) 135MB -
  latest/beta:      ↑                            
  latest/edge:      5.2.1 2022-11-22 (570) 135MB -
installed:          5.2.1            (567) 135MB -
```

### Output of `snap connections $snap_name`

```shell
Interface               Plug                                       Slot                            Notes
audio-playback          mattermost-desktop:audio-playback          :audio-playback                 -
audio-record            mattermost-desktop:audio-record            -                               -
camera                  mattermost-desktop:camera                  -                               -
content[gnome-42-2204]  mattermost-desktop:gnome-42-2204           gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   mattermost-desktop:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    mattermost-desktop:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   mattermost-desktop:sound-themes            gtk-common-themes:sound-themes  -
desktop                 mattermost-desktop:desktop                 :desktop                        -
desktop-legacy          mattermost-desktop:desktop-legacy          :desktop-legacy                 -
gsettings               mattermost-desktop:gsettings               :gsettings                      -
home                    mattermost-desktop:home                    :home                           -
login-session-observe   mattermost-desktop:login-session-observe   -                               -
network                 mattermost-desktop:network                 :network                        -
network-bind            mattermost-desktop:network-bind            :network-bind                   -
opengl                  mattermost-desktop:opengl                  :opengl                         -
pulseaudio              mattermost-desktop:pulseaudio              :pulseaudio                     -
removable-media         mattermost-desktop:removable-media         :removable-media                manual
screen-inhibit-control  mattermost-desktop:screen-inhibit-control  :screen-inhibit-control         -
shared-memory           mattermost-desktop:shmem                   :shared-memory                  -
unity7                  mattermost-desktop:unity7                  :unity7                         -
wayland                 mattermost-desktop:wayland                 :wayland                        -
x11                     mattermost-desktop:x11                     :x11                            -
```

### Output of `snap version`

```shell
snap    2.57.5+22.04
snapd   2.57.5+22.04
series  16
ubuntu  22.04
kernel  5.15.0-10052-tuxedo
```

### Relevant log output

```shell
[27636.781508] audit: type=1400 audit(1669220336.324:2663): apparmor="DENIED" operation="mkdir" profile="snap.mattermost-desktop.mattermost-desktop" name="/home/mm/snap/mattermost-desktop/514/" pid=4850 comm="ThreadPoolForeg" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
[27708.153317] audit: type=1400 audit(1669220407.697:2664): apparmor="DENIED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/proc/31355/oom_score_adj" pid=4850 comm="ThreadPoolSingl" requested_mask="wc" denied_mask="wc" fsuid=1000 ouid=1000
[27708.246349] audit: type=1400 audit(1669220407.793:2667): apparmor="DENIED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/proc/31369/oom_score_adj" pid=4850 comm="ThreadPoolSingl" requested_mask="wc" denied_mask="wc" fsuid=1000 ouid=1000
[27708.267099] audit: type=1400 audit(1669220407.813:2670): apparmor="DENIED" operation="open" profile="snap.mattermost-desktop.mattermost-desktop" name="/proc/31382/oom_score_adj" pid=4850 comm="ThreadPoolSingl" requested_mask="wc" denied_mask="wc" fsuid=1000 ouid=1000
[27785.937409] audit: type=1400 audit(1669220485.486:2673): apparmor="DENIED" operation="mkdir" profile="snap.mattermost-desktop.mattermost-desktop" name="/home/mm/snap/mattermost-desktop/514/" pid=4850 comm="ThreadPoolForeg" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
```

**Comment by kenvandine** [comment] 2022-11-23 19:56
I can't reproduce this on Ubuntu 22.04 or 22.10, running stock Ubuntu Desktop with GNOME.  What desktop environment are you using?

**Comment by mm-may** [comment] 2022-11-23 21:22
Two different computers (and users), one with Ubuntu (Gnome), the other one Kubuntu (KDE), both 22.04 with all updates applied.

But I now found a workaround: I moved my `~/snap/mattermostmattermost-desktop` directory somewhere else. Setting up the connections to the servers from scratch then worked. So it seems to be a migration/update issue from older versions? At least one of the computers was running Ubuntu 20.04 before and I upgraded a couple of weeks ago. But things worked until the Mattermost-Desktop version 5.2

**Comment by mm-may** [comment] 2022-12-08 09:35
Well, I followed a similar approach, deleting the whole config dir `~/snap/mattermostmattermost-desktop` manually, setting up servers anew. But that only worked until the next update of the snap.

**Comment by krehfeld** [comment] 2022-12-22 17:00
I have the same issue with mattermost v  latest/stable:    5.2.2 2022-12-12 (578) on Ubuntu 20.04.

**Comment by DanielHeath** [comment] 2023-01-17 23:18
I tested this just now.

When running mattermost-desktop from the CLI I can download files.
When running mattermost-desktop via `synapse` (which was launched by an i3 keyboard shortcut), I can't download any files (everything is immediately cancelled).

The running version of mattermost is: `/snap/mattermost-desktop/578/opt/Mattermost/mattermost-desktop`

Syslog contains:
```
Jan 18 10:15:33 drh-workstation kernel: [590419.293010] audit: type=1400 audit(1673997333.852:1402): apparmor="DENIED" operation="mkdir" profile="snap.mattermost-desktop.mattermost-desktop" name="/home/daniel/snap/mattermost-desktop/514/" pid=698800 comm="ThreadPoolForeg" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
```

Reloading i3 does not fix the issue (about to test a restart, but that's likely to kill the browser I'm typing this into)

**Comment by DanielHeath** [comment] 2023-01-17 23:20
Killing i3 also does not fix the issue.

**Comment by DanielHeath** [comment] 2023-01-17 23:41
Even after a full system reboot, no dice.

However, I do find something promising:
```
  $ find  /etc/systemd/ | grep mattermost

/etc/systemd/system/default.target.wants/snap-mattermost\x2ddesktop-567.mount
/etc/systemd/system/default.target.wants/snap-mattermost\x2ddesktop-578.mount
/etc/systemd/system/multi-user.target.wants/snap-mattermost\x2ddesktop-567.mount
/etc/systemd/system/multi-user.target.wants/snap-mattermost\x2ddesktop-578.mount
/etc/systemd/system/snap-mattermost\x2ddesktop-567.mount
/etc/systemd/system/snap-mattermost\x2ddesktop-578.mount
```

/etc/systemd/system/default.target.wants/snap-mattermost\\x2ddesktop-567.mount
```
[Unit]
Description=Mount unit for mattermost-desktop, revision 567
Before=snapd.service
After=zfs-mount.service

[Mount]
What=/var/lib/snapd/snaps/mattermost-desktop_567.snap
Where=/snap/mattermost-desktop/567
Type=squashfs
Options=nodev,ro,x-gdu.hide,x-gvfs-hide
LazyUnmount=yes

[Install]
WantedBy=default.target multi-user.target

```

/etc/systemd/system/default.target.wants/snap-mattermost\\x2ddesktop-578.mount
```
[Unit]
Description=Mount unit for mattermost-desktop, revision 578
Before=snapd.service
After=zfs-mount.service

[Mount]
What=/var/lib/snapd/snaps/mattermost-desktop_578.snap
Where=/snap/mattermost-desktop/578
Type=squashfs
Options=nodev,ro,x-gdu.hide,x-gvfs-hide
LazyUnmount=yes

[Install]
WantedBy=default.target multi-user.target

```

/etc/systemd/system/multi-user.target.wants/snap-mattermost\\x2ddesktop-567.mount
```
[Unit]
Description=Mount unit for mattermost-desktop, revision 567
Before=snapd.service
After=zfs-mount.service

[Mount]
What=/var/lib/snapd/snaps/mattermost-desktop_567.snap
Where=/snap/mattermost-desktop/567
Type=squashfs
Options=nodev,ro,x-gdu.hide,x-gvfs-hide
LazyUnmount=yes

[Install]
WantedBy=default.target multi-user.target

```

/etc/systemd/system/multi-user.target.wants/snap-mattermost\\x2ddesktop-578.mount
```
[Unit]
Description=Mount unit for mattermost-desktop, revision 578
Before=snapd.service
After=zfs-mount.service

[Mount]
What=/var/lib/snapd/snaps/mattermost-desktop_578.snap
Where=/snap/mattermost-desktop/578
Type=squashfs
Options=nodev,ro,x-gdu.hide,x-gvfs-hide
LazyUnmount=yes

[Install]
WantedBy=default.target multi-user.target

```

/etc/systemd/system/snap-mattermost\\x2ddesktop-567.mount
```
[Unit]
Description=Mount unit for mattermost-desktop, revision 567
Before=snapd.service
After=zfs-mount.service

[Mount]
What=/var/lib/snapd/snaps/mattermost-desktop_567.snap
Where=/snap/mattermost-desktop/567
Type=squashfs
Options=nodev,ro,x-gdu.hide,x-gvfs-hide
LazyUnmount=yes

[Install]
WantedBy=default.target multi-user.target

```

/etc/systemd/system/snap-mattermost\\x2ddesktop-578.mount
```
[Unit]
Description=Mount unit for mattermost-desktop, revision 578
Before=snapd.service
After=zfs-mount.service

[Mount]
What=/var/lib/snapd/snaps/mattermost-desktop_578.snap
Where=/snap/mattermost-desktop/578
Type=squashfs
Options=nodev,ro,x-gdu.hide,x-gvfs-hide
LazyUnmount=yes

[Install]
WantedBy=default.target multi-user.target
```

In syslog:
```
Jan 18 10:23:29 drh-workstation kernel: [   94.281522] audit: type=1400 audit(1673997809.601:217): apparmor="DENIED" operation="mkdir" profile="snap.mattermost-desktop.mattermost-desktop" name="/home/daniel/snap/mattermost-desktop/514/" pid=7142 comm="ThreadPoolForeg" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000
```

Firstly, why are every systemd unit duplicated for v567 vs v578? Did something fail to clean up the old ones?

Secondly, why does snapd version `2.57.5+22.04ubuntu0.1` set the apparmor profile this way?

**Comment by DanielHeath** [comment] 2023-01-17 23:54
So - when I run `mattermost-desktop` from a terminal, pstree looks like:

`systemd───systemd───gnome-terminal-───bash───mattermost-desk───mattermost-desk───9*[{mattermost-desk}]`

However, when I run it via synapse, it looks like:

`systemd───mattermost-desk───mattermost-desk───mattermost-desk───15*[{mattermost-desk}]`

The former has access to save files, but the latter does not.

**Comment by DanielHeath** [comment] 2023-01-31 22:07
Just hit this bug running mattermost-desktop from a terminal, so that's not it either.

**Comment by DanielHeath** [comment] 2023-01-31 23:25
"menu -> settings -> change download directory -> choose your actual ~/Downloads" appears to fix it completely.

Not sure why it was set to something other than `~/Downloads` in the past.

**Comment by jnsgruk** [comment] 2023-02-01 11:14
Ah, interesting, thanks for finding that.

@kenvandine / @diddledani looks like this config is set in `~/.config/Mattermost/config.json` - there is a key in there named `downloadLocation`, e.g.

```json
{
...
"downloadLocation": "/home/jon/downloads",
...
}
```

I wonder if there is a sensible way we could set this during a first install at least?

**Comment by DanielHeath** [comment] 2023-02-02 01:59
Given it's been reported by a few people, perhaps a check on startup - if writing a test file to the download directory fails, reset that setting to the default?

**Comment by kenvandine** [comment] 2023-02-07 18:47
I think this would actually need to be fixed in mattermost-desktop upstream.  The getDefaultDownloadLocation function just returns os.homedir()/Downloads right now.  It should really use the XDG API to get the user's defined downloads dir.

**Comment by merlijn-sebrechts** [comment] 2023-02-25 15:28
Can we use the homeishome launcher as workaround right now? https://forum.snapcraft.io/t/the-homeishome-launcher-fix-snapped-apps-that-wrongly-referring-to-the-users-real-home-directory-instead-of-home/19763

**Comment by merlijn-sebrechts** [comment] 2023-03-15 15:29
Wow, that's amazing! Great work @jnsgruk!

Will this fix it for everyone, or only new installs?

**Comment by merlijn-sebrechts** [comment] 2023-03-15 15:32
Would it be possible to create a script that fixes existing installs? We can be very conservative: only overwrite the setting when it points to the obviously-bad `~/snap/mattermost-desktop/current/Downloads`?

**Comment by diddledani** [comment] 2023-03-15 17:15
Really good work! If we have the ability to script the setting change then we can possibly add a post-refresh hook script to conditionally move the data and update the setting. I'd need to double check if post refresh scripts support user data access. If it doesn't (I suspect it doesn't so we'll need to do this second method) then we can add a command-chain script to do the move and setting change.

**Comment by jnsgruk** [comment] 2023-03-15 17:31
This will only fix new installs -- like the idea of a post-refresh hook or command-chain, would be keen to see how that looks. Bit above my snapping pay grade to date!

**Closed** 2023-03-24 12:51 UTC
Labels: bug
